[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "test/bin" },
    { access = "read", path = "out" },
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_ARBITRUM}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
